"""First migration

Revision ID: 845d5c70eaf2
Revises: 
Create Date: 2025-03-18 16:06:15.750758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845d5c70eaf2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('street_number', sa.String(length=16), nullable=True),
    sa.Column('street_name', sa.String(length=64), nullable=True),
    sa.Column('neighborhood', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('postal_code', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('country_code', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address_line_1', sa.String(length=128), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_id'), 'address', ['id'], unique=False)
    op.create_table('location',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_id'), 'location', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=21), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('resource',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.Enum('UNKNOWN', 'AMBULANCE', 'POLICE', 'FIRETRUCK', name='resourcetypeenum'), nullable=True),
    sa.Column('actual_address', sa.Uuid(), nullable=True),
    sa.Column('actual_location', sa.Uuid(), nullable=True),
    sa.Column('normal_address', sa.Uuid(), nullable=True),
    sa.Column('normal_location', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('UNKNOWN', 'AVAILABLE', 'BUSY', 'MAINTENANCE', name='resourcestatusenum'), nullable=True),
    sa.Column('responsible', sa.String(length=128), nullable=True),
    sa.Column('telephone', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actual_address'], ['address.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actual_location'], ['location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['normal_address'], ['address.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['normal_location'], ['location.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_id'), 'resource', ['id'], unique=False)
    op.create_table('emergency',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='prioritytype'), nullable=True),
    sa.Column('emergency_type', sa.Enum('FIRE', 'MEDICAL', 'ACCIDENT', 'NATURAL_DISASTER', 'OTHER', name='emergencytype'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'SOLVED', 'ARCHIVED', name='statustype'), nullable=True),
    sa.Column('location_emergency', sa.Uuid(), nullable=True),
    sa.Column('address_emergency', sa.Uuid(), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('location_resource', sa.Uuid(), nullable=True),
    sa.Column('address_resource', sa.Uuid(), nullable=True),
    sa.Column('destination_id', sa.Uuid(), nullable=True),
    sa.Column('location_destination', sa.Uuid(), nullable=True),
    sa.Column('address_destination', sa.Uuid(), nullable=True),
    sa.Column('name_contact', sa.String(length=128), nullable=True),
    sa.Column('telephone_contact', sa.String(length=128), nullable=True),
    sa.Column('id_contact', sa.String(length=128), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['address_destination'], ['address.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['address_emergency'], ['address.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['address_resource'], ['address.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['destination_id'], ['resource.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_destination'], ['location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_emergency'], ['location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_resource'], ['location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_id'), 'emergency', ['id'], unique=False)
    op.create_table('emergencyresourcelink',
    sa.Column('emergency_id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['emergency_id'], ['emergency.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('emergency_id', 'resource_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emergencyresourcelink')
    op.drop_index(op.f('ix_emergency_id'), table_name='emergency')
    op.drop_table('emergency')
    op.drop_index(op.f('ix_resource_id'), table_name='resource')
    op.drop_table('resource')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_location_id'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_address_id'), table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###
